### ISSUE TITLE
Publish APK at Github?

### ISSUE THREAD

**Issue by IzzySoft** [Kampijo/Reminder#7]
Would you mind attaching the `.apk` file to the corresponding `releases/` (starting with the latest one is fine, no need for older releases), so folks without Playstore can use your app? Thanks in advance!

**Comment by IzzySoft** [comment]
Hm, any reply?

**Comment by Kampijo** [comment]
Sorry about this. Gonna get on it when I have the time. Thanks!

**Comment by IzzySoft** [comment]
@Kampijo thanks for adding the APK again! Unfortunately, it is no longer signed?

**Comment by Kampijo** [comment]
That's weird, I swear I signed it. Let me confirm.

**Comment by IzzySoft** [comment]
I've got an error that no certificates were found.

**Comment by Kampijo** [comment]
Ah I might know what's going on. I'm signing with new v2 scheme without first signing v1 for pre-7.0.

I'll rebuild and re-upload as soon as possible.

**Comment by IzzySoft** [comment]
Thanks a lot! Simply ping me by updating this issue when done, so I'll test it ASAP and give feedback.

**Comment by IzzySoft** [comment]
Any update that I missed? Is it signed now so I should retry?

**Comment by IzzySoft** [comment]
Just tried again, and still not signed :disappointed:
